= The `NoOpLogger`

The `NoOpLogger` is a logger implementation provided with Objectos Logging.
It is a no-operation logger. All of its logging methods do no operation when invoked.

Even though it performs no logging operation, the `NoOpLogger` can be useful
during the development of a Java application.

This section describes some of its uses.

== Obtaining the singleton instance

The `NoOpLogger` is a no-operation logger implementation. As it does nothing, it has no state
either. It provides a singleton instance since it can be safely reused. You access it by
invoking the static `getInstance()` method:

[,java]
----
var logger = NoOpLogger.getInstance();
----

== Use it as a _default_ value

In classes where the `Logger` is defined as a mutable field, it is recommended you provide
the `NoOpLogger` instance as a _default_ logger implementation.

We saw two examples in the ilink:logging/logging-guide/logger[obtaining the `Logger` interface]
section:

* via the setter method; and
* via static factory.

As a quick reminder, let's see the _setter method_ strategy:

[,java]
----
import objectos.logging.*;

public class Setter {
  private Logger logger = NoOpLogger.getInstance();

  void setLogger(Logger logger) {
    if (logger == null) {
      throw new NullPointerException("logger == null");
    }

    this.logger = logger;
  }
}
----

Notice how the `logger` field is initialized with the `NoOpLogger` singleton instance.
It can be altered via the `setLogger()` method.

== Use it by subclassing

The `NoOpLogger` is also designed so it can be used by subclassing it.

For example, suppose you wish to provide a default `Logger` implementation that does a little
work, say print to the standard output. You can do it by extending the `NoOpLogger`.

[,java]
----
import objectos.logging.*;

public class Service {
  static final Event0 START = Event0.info();

  Logger logger = new NoOpLogger() {
    @Override
    public void log(Event0 event) {
      if (event == START) {
        System.out.println(event);
      }
    }
  };

  public void start() {
    logger.log(START);
  }

  void setLogger(Logger logger) {
    if (logger == null) {
      throw new NullPointerException("logger == null");
    }

    this.logger = logger;
  }
}
----
