= Limitations

The Collections API provided by Objectos Util is not a _general purpose_ one.
Instead, Objectos Util provides a _special purpose_ Collections API.
The primary goal of Objectos Util is to provide a Collections API to the Objectos libraries themselves.

As such, and depending on your requirements, some, if not all, of its characteristics may be perceived as limitations. 

In this article we will give a summary of the characteristics you should be aware of _before_ using Objectos Util in your projects.

== Linear probing

Objectos Util uses the linear probing form of the open addressing scheme for hash collision resolution. 
All of the hash-based implementations use such scheme, namely:

* `GrowableSet`
* `GrowableMap`
* `GrowableSequencedMap`
* `UnmodifiableSet`
* `UnmodifiableMap`
* `UnmodifiableSequencedMap`

This means performance degrades as the number of hash collisions increases.

The use of the JDK provided implementations is _highly recommended_ if you anticipate this situation.

The JDK provided implementations:

* `java.util.HashMap`
* `java.util.HashSet`

Offer hash collision attack mitigation since JDK 8.
You can read more about it in https://openjdk.org/jeps/180[JEP 180].

== Implementations reject `null` values

The following will not allow `null` elements:

* `GrowableList`
* `GrowableSet`
* `UnmodifiableList`
* `UnmodifiableSet`

The following will not allow `null` keys nor `null` values:

* `GrowableMap`
* `GrowableSequencedMap`
* `UnmodifiableMap`
* `UnmodifiableSequencedMap`

Use the JDK provided implementations if you require:

* `null` elements; or
* permitting `null` keys or `null` values.

== `Iterator` instances do not throw `ConcurrentModificationException`

Consider the following code using JDK's `ArrayList`:

[,java]
----
var list = new ArrayList<String>();

list.add("A");
list.add("B");

var it = list.iterator();

// modification after iterator was created
list.add("C");

assertTrue(it.hasNext());
assertEquals(it.next(), "A"); // throws CME
----

The code fails at the last statement as a `ConcurrentModificationException` is thrown.

The Objectos Util implementations do NOT behave this way.
In other words, all of the returned `Iterator` instances are NOT fail-fast as defined by the `ConcurrentModificationException`.

If you replace the `ArrayList` with a `GrowableList` no exception is thrown.

[,java]
----
var list = new GrowableList<String>();

list.add("A");
list.add("B");

var it = list.iterator();

list.add("C");

assertTrue(it.hasNext());
assertEquals(it.next(), "A");
// no exception thrown
----

This may be problematic if the list is accessed by multiple threads.

Note that _all_ of the returned `Iterator` instances has this behavior.
For example, it includes the iterators returned by:

* `Map::values`
* `Map::keySet`
* `Map::entrySet`

== Unsupported or un-implemented operations

You should know that some of the operations specified by either:

* `java.util.Collection`;
* `java.util.List`;
* `java.util.Set`; or
* `java.util.Map`.

Might not be supported or might not have been implemented.

Please refer to the elink:v0004/api/index[Javadocs].