= About logging

A logging library let's you emit messages about the events that take place during
a program execution. These messages usually contain the time of the event,
the source of the event (in Java programs the name of class of the object from
which the message was emitted) and the severity of the event. Additional information
related to the event may be also added to the message at the developer's discretion.

These messages may be written to a log. The log may be persistent such as a log file. The
log may be ephemeral such as messages directed to a console. Messages
may be filtered out before being written to the log; for example, only messages
above a certain severity level may be sent to the log.

The acts of emitting, filtering and storing messages in a program
are collectively called logging.

== Messages to inform

A log may contain purely informational messages such as:

* a SQL server started successfully (i.e., it is ready for connections);
* a HTTP server sent a 404 response; or
* a scheduled job completed successfully.

These informational messages can help developers, at development time, assert that
the application is functioning as expected. Similarly, these messages can be used
by a system operator to verify that the system is running correctly while in production.

== Messages to warn about potential issues

A log may also contain messages indicating that a problem might occur to a running
application if no action is taken. These can be health-related messages such as
possible resource exhaustion. Or perhaps they can be security-related such as
suspicious activity. Some examples:

* a query to the database took more than a certain number of milliseconds;
* few free slots remain in the job scheduler; or
* too many invalid requests from a certain client.

== Message describing errors

Applications will eventually not work as expected. As pointed out before, it could be
from resource exhaustion. Other reasons might also include (but are in no way limited to):

* programming errors;
* invalid or insufficient system permissions; or
* hardware failures.

Therefore, the log may also contain error messages such as:

* the application could not start as the configured network port `P` is already in use;
* a HTTP server could not serve a file `F` as its system's process does not have the
required permissions to read it;
* a scheduled job fails as it tries to use `null` as if it were an object; or
* a scheduled job fails as the Java virtual machine cannot allocate an object as
it ran out of memory.

In Java programs these messages can include the stack trace from a `Throwable` object.
Note, however, that inclusion of stack traces are not restricted to error messages.

== Debugging messages

While the log may contain the message that an error has occurred, the developer
might need additional information in order to reproduce the error in a development
environment. This may also be necessary when it is impossible or impratical to attach
a debugger to a running application. In this case, the log may also contain messages
intended for debugging purposes. Some examples are:

* the failing service was invoked with such and such arguments;
* a related method completed normally returning such value; or
* this code path has been executed.

== Monitoring messages

Finally, the log may also contain messages that cover non-functional requirements.
In a way, these messages can be classified as being both informational
and for debugging purposes.

As an example, suppose you believe a library upgrade or a code refactoring
will improve numbers such as latency or throughput. How can you confirm whether
or not the changes improved the numbers? This involves some collecting and statistical
analysis which is beyond the scope of a logging library. However for data to be collected
and analyzed it must exist in the first place.

== Summary

In this section we discussed what logging libraries are and showed some examples
of messages you might want to log using such libraries.

One thing in common to all the examples is that it is the developer job to:

* decide what events to log;
* define the severity of the logged event; and
* what information should be logged with the event.
