= Constructor annotations

Use the `annotation` instruction to include _annotations_ to your constructor declaration.

The following Objectos Code:

[,java]
----
import objectos.code.ClassTypeName;
import objectos.code.JavaTemplate;

public class ConstructorAnnotations01 extends JavaTemplate {
  static final ClassTypeName MY_ANNO
      = ClassTypeName.of("com.example.annotations", "MyAnnotation");

  @Override
  protected final void definition() {
    autoImports();

    classDeclaration(
      name("ConstructorAnnotations"),

      constructor(
        annotation(MY_ANNO),
        PUBLIC
      )
    );
  }
}
----

Generates:

[,java]
----
import com.example.annotations.MyAnnotation;

class ConstructorAnnotations {
  @MyAnnotation
  public ConstructorAnnotations() {}
}
----

== Multiple annotations

Use multiple `annotation` instructions to add multiple annotations to your constructor declaration. 

The following Objectos Code:

[,java]
----
import objectos.code.ClassTypeName;
import objectos.code.JavaTemplate;

public class ConstructorAnnotations02 extends JavaTemplate {
  static final ClassTypeName ANNO_A
      = ClassTypeName.of("com.example.annotations", "AnnotationA");
  static final ClassTypeName ANNO_B
      = ClassTypeName.of("com.example.annotations", "AnnotationB");
  static final ClassTypeName ANNO_C
      = ClassTypeName.of("com.example.annotations", "AnnotationC");

  @Override
  protected final void definition() {
    autoImports();

    classDeclaration(
      name("ConstructorAnnotations"),

      constructor(
        annotation(ANNO_A),
        annotation(ANNO_B),
        annotation(ANNO_C),
        PUBLIC
      )
    );
  }
}
----

Generates the following Java class declaration:

[,java]
----
import com.example.annotations.AnnotationA;
import com.example.annotations.AnnotationB;
import com.example.annotations.AnnotationC;

class ConstructorAnnotations {
  @AnnotationA
  @AnnotationB
  @AnnotationC
  public ConstructorAnnotations() {}
}
----

== Including annotations programmatically

Use the `include` instruction if you need to generate a different set of annotations based on a condition.

In the following Objectos Code:

[,java]
----
import java.util.concurrent.ThreadLocalRandom;
import objectos.code.ClassTypeName;
import objectos.code.JavaTemplate;

public class ConstructorAnnotations03 extends JavaTemplate {
  static final ClassTypeName ANNO_A
      = ClassTypeName.of("com.example.annotations", "AnnotationA");
  static final ClassTypeName ANNO_B
      = ClassTypeName.of("com.example.annotations", "AnnotationB");
  static final ClassTypeName ANNO_C
      = ClassTypeName.of("com.example.annotations", "AnnotationC");

  @Override
  protected final void definition() {
    autoImports();

    classDeclaration(
      name("ConstructorAnnotations"),

      constructor(
        include(this::annotations),
        PUBLIC, parameter(INT, name("value"))
      )
    );
  }

  private void annotations() {
    annotation(ANNO_A);

    if (shouldHaveAnnoB()) {
      annotation(ANNO_B);
    }

    annotation(ANNO_C);
  }

  private boolean shouldHaveAnnoB() {
    return ThreadLocalRandom.current().nextBoolean();
  }
}
----

Notice the `include` instruction in the `constructor` instruction:

[,java]
----
constructor(
  include(this::annotations),
  PUBLIC, parameter(INT, name("value"))
)
----

The annotations are defined in the private `annotations` method:

[,java]
----
private void annotations() {
  annotation(ANNO_A);

  if (shouldHaveAnnoB()) {
    annotation(ANNO_B);
  }

  annotation(ANNO_C);
}
----

So, depending on the value returned by the `shouldHaveAnnoB` method, the following are generated:

[,java]
----
// shouldHaveAnnoB() returns true
import com.example.annotations.AnnotationA;
import com.example.annotations.AnnotationB;
import com.example.annotations.AnnotationC;

class ConstructorAnnotations {
  @AnnotationA
  @AnnotationB
  @AnnotationC
  public ConstructorAnnotations(int value) {}
}

// shouldHaveAnnoB() returns false
import com.example.annotations.AnnotationA;
import com.example.annotations.AnnotationC;

class ConstructorAnnotations {
  @AnnotationA
  @AnnotationC
  public ConstructorAnnotations(int value) {}
}
----
