= Installation

In order to get started with Objectos you need to have it installed in your system.

As of the current release there is only one supported installation method:

* add Objectos to an existing Maven project.

== System requirements

Objectos requires JDK 17 or later.

== Import the Objectos BOM POM

Using the Objectos BOM POM is the recommended way of adding Objectos to your
project. You can import it by declaring it in the `dependencyManagement`
section of your project's POM file like so:

[,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>br.com.objectos</groupId>
            <artifactId>objectos-bom</artifactId>
            <version>0.2.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

== Use Objectos components

The next step is to add Objectos components to your project.
Since you have the Objectos BOM imported you do not need to specify the version
for each of the added components.

For instance, to add Objectos Lang to your project, you would declare it
in the `dependencies` section of your projects's POM file like so:

[,xml]
----
<dependencies>
    <dependency>
        <groupId>br.com.objectos</groupId>
        <artifactId>objectos-lang</artifactId>
    </dependency>
</dependencies>
----

If your application is modular, you should also add the `requires`
directive to your `module-info.java` file like so:

[,java]
----
module my.module {
  requires objectos.lang;
}
----
