= Using the `Logger` interface

After declaring your event instances you can emit log messages
by using them with the `Logger` interface.

In this section we will give you instructions on how to use the
`Logger` interface.

== Obtaining `Logger` instances

As seen in the previous section events are bound to a particular class as, by default,
their source is set to the canonical name of the class in which the event was declared.

The first thing to know about logger instances is that, unlike events,
logger instances _are not bound_ to a particular class. Typically
logger instances *will not be* `static final` fields of a class.

Next we will discuss the recommended strategies for obtaining logger instances.

=== Via constructor

This is the recommended way to obtain logger instances. In particular for
the long-lived objects of your Java application.

[,java]
----
import objectos.logging.*;

public class Service {
  private final Logger logger;

  Service(Logger logger) {
    this.logger = logger;
  }
}
----

=== Via method parameter

If you are concerned about object size and garbage creation, storing the logger
in an instance field might be problematic. If the class or the method where the
logging takes place is not part of a public API, you can pass the logger via a method parameter.

[,java]
----
import objectos.logging.*;

public class ShortLived {
  void internalMethod(Logger logger) {
    // use logger here
  }
}
----

=== Via setter method

The previous option might not work for you if the method where logging takes place
is part of the exported API. In this case you can use a setter method for the logger instance.

[,java]
----
import objectos.logging.*;

public class Setter {
  private Logger logger = NoOpLogger.getInstance();

  void setLogger(Logger logger) {
    if (logger == null) {
      throw new NullPointerException("logger == null");
    }

    this.logger = logger;
  }
}
----

You must be aware this strategy is error-prone:

* you must null-check before setting the logger field value;
* you must set the logger to a default value to avoid null-pointer exceptions. Typically this
will be the link:href:v0001.logging.TheNoOpLoggerIndex[`NoOpLogger`]; and
* depending on your requirements, you might need to synchronize the access.

=== Via static factory

As a last resort, you can create your own static factory. Since we consider it a last
resort, Objectos Logging does not provide one out-of-the-box. A minimal example is:

[,java]
----
import objectos.logging.*;

public final class StaticLogger {
  private static Logger LOGGER = NoOpLogger.getInstance();

  private StaticLogger() {}

  public static Logger get() {
    return LOGGER;
  }

  public static void set(Logger logger) {
    if (logger == null) {
      throw new NullPointerException("logger == null");
    }

    LOGGER = logger;
  }
}
----

During application initialization, set the static factory with a proper logger instance.
Then, in the class where logging is needed, you can obtain the logger from the factory.

[,java]
----
import objectos.logging.*;

public class Service {
  private static final Logger LOGGER = StaticLogger.get();
}
----

Consider using this strategy as a last resort as it can make using loggers
for debugging more complicated. Also this strategy is error-prone for the same reasons as
the _setter method_ strategy.

== Logging events

Now that you have:

* your events declared; and
* obtained a logger instance.

You can emit log messages.

To emit log messages you invoke one of the `log` methods from the `Logger` interface.
The `Logger` interface provides a different `log` method for each `Event` subclass.

=== `Event0`

Events of the `Event0` are not parameterized:

[,java]
----
static final Event0 EVENT = Event0.info();
----

To emit a log message you invoke the `log` method passing the event as a parameter:

[,java]
----
logger.log(EVENT);
----

=== `Event1`

Events of the `Event1` class have a single type argument.
In order to emit a log message of these events you must pass an object
of the same type as the type argument of the event.

For example, if the event is parameterized with a hypothetical `Result` type:

[,java]
----
static final Event1<Result> EVENT = Event1.info();
----

You must invoke the `log` method passing, along with the event itself, a `Result` instance:

[,java]
----
Result result = computeResult();
logger.log(EVENT, result);
----

=== `Event2`

In a similar way, invoking the `log` method with `Event2` events requires you to
pass, along with the event instance itself, two additional objects.
The two objects must have the same types, in order, as those declared as
type arguments of the event.

So, if the event is declared as:

[,java]
----
static final Event2<Data, Result> EVENT = Event2.info();
----

Then the `log` method must be invoked with the arguments in the following order:

* the event itself;
* a `Data` object; and
* a `Result` object.

[,java]
----
Data input = getInput();
Result result = compute(input);
logger.log(EVENT, input, result);
----

If we were to reverse the order of the type arguments in the event declaration:

[,java]
----
static final Event2<Result, Data> EVENT = Event2.info();
----

Then the `log` method invocation needs to be changed to:

[,java]
----
logger.log(EVENT, result, input);
----

=== `Event3`

Logging `Event3` events work in a similar way as `Event2`. If the event is parameterized,
in order, with the hypothetical types `A`, `B` and `C`:

[,java]
----
static final Event3<A, B, C> EVENT = Event3.info();
----

Then a `log` method invocation would need to be:

[,java]
----
logger.log(EVENT, a, b, c);
----

Where `a`, `b` and `c` are objects of types `A`, `B` and `C` respectively.
