= Objectos Code
:toc-title: Overview

Objectos Code is a library for generating Java source code.

It introduces the concept of a "pure Java template";
it feels like a traditional text-based template except it is a regular Java class.

== Tutorial

This tutorial will give you an introduction on how to generate Java source code using Objectos Code.

=== An empty class

Let's start by generating a class that has an empty body.
In other words, we want to generate the following:

[,java]
----
class Tutorial {}
----

To use Objectos Code you have to:

- extend the `JavaTemplate` class; and
- provide the implementation of the `definition` method.

In the latter, you use the provided embedded domain-specific language.
Like so:

[,java]
----
import objectos.code.JavaTemplate;

public class Tutorial extends JavaTemplate {
  @Override
  protected final void definition() {
    _class("Tutorial");
    body();
  }
}
----

It starts by invoking the `_class` method.
Notice that, as `class` is a reserved keyword in Java, the method name starts with the '_' (underscore) character.
The string `"Tutorial"`, the name of the class we want to generate, is passed as the argument to the `_class` method.

Next, we invoked the `body` method.
No arguments were passed as we want to generate a class with an empty body.

Right.
Let's move to the next step.

=== Adding a package declaration

[,java]
----
package com.example;

class Tutorial {}
----

[,java]
----
import objectos.code.JavaTemplate;

public class Tutorial extends JavaTemplate {
  @Override
  protected final void definition() {
    _package("com.example");
  
    _class("Tutorial");
    body();
  }
}
----

=== Adding class modifiers

We want our class:

- to be public; and
- to be annotated with a marker annotation.

[,java]
----
package com.example;
----

[,java]
----
import java.io.IOException;
import objectos.code.JavaTemplate;

public class MyException extends JavaTemplate {
  @Override
  protected final void definition() {
    code(
      _package("com.example"),

      autoImports(),

      _public(), _class("MyException"), _extends(), t(IOException.class), body()
    );
  }
}
----

It can be used to generate the following Java code:

[,java]
----
package com.example;

import java.io.IOException;

public class MyException extends IOException {}
----

== Installation

To use Objectos Code in your project add the following to your POM:

[,xml]
----
<dependencies>
    <dependency>
        <groupId>br.com.objectos</groupId>
        <artifactId>objectos-code</artifactId>
    </dependency>
</dependencies>
----

This assumes you are using the ilink:intro/install[Objectos BOM POM].
