= Objectos Code
:toc-title: Overview

Objectos Code is a library for generating Java source code.

It introduces the concept of a "pure Java template";
it feels like a traditional text-based template except it is a regular Java class.

== Tutorial

This tutorial will give you an introduction on how to generate Java source code using Objectos Code.

=== An empty class

Let's start by generating a class that has an empty body.
In other words, we want to generate the following:

[,java]
----
class Tutorial {}
----

To use Objectos Code you have to:

- extend the `JavaTemplate` class; and
- provide the implementation of the `definition` method.

In the latter, you use the provided embedded domain-specific language.
Like so:

[,java]
----
import objectos.code.JavaTemplate;

public class Tutorial extends JavaTemplate {
  @Override
  protected final void definition() {
    _class("Tutorial");
    body();
  }
}
----

It starts by invoking the `_class` method.
Notice that, as `class` is a reserved keyword in Java, the method name starts with the '_' (underscore) character.
The string `"Tutorial"`, the name of the class we want to generate, is passed as the argument to the `_class` method.

Next, we invoked the `body` method.
No arguments were passed as we want to generate a class with an empty body.

Right.
Let's move to the next step.

=== The package declaration

Let's add a package declaration to our generated Java source file.
We want our class to be in the `com.example` package, like so:

[,java]
----
package com.example;

class Tutorial {}
----

In our template, we invoke the `_package` method:

[,java]
----
import objectos.code.JavaTemplate;

public class Tutorial extends JavaTemplate {
  @Override
  protected final void definition() {
    _package("com.example");
  
    _class("Tutorial");
    body();
  }
}
----

Once again, the `_package` method name begins with an underscore character.

=== The class modifiers

Let's add modifiers to our class.

We want the generated class to be the following:

[,java]
----
package com.example;

public final class Tutorial {}
----

Our class is now both `public` and `final`.
So we need to add the same "keywords" to our template: 

[,java]
----
import objectos.code.JavaTemplate;

public class Tutorial extends JavaTemplate {
  @Override
  protected final void definition() {
    _package("com.example");

    _public();
    _final();
    _class("Tutorial");
    body();
  }
}
----

With each "keyword" sitting at a different line, our template does not look like a regular Java file.
Let's improve that.

=== Optional: the `code` method

We can group all of our template instructions in a single `code` method invocation like so:

[,java]
----
import objectos.code.JavaTemplate;

public class Tutorial extends JavaTemplate {
  @Override
  protected final void definition() {
    code(
      _package("com.example"),

      _public(), _final(), _class("Tutorial"), body()
    );
  }
}
----

Notice that the instructions are now arguments to the `code` method.
Therefore, each instruction is now separated with a comma.

Alternatively, you can use a `@formatter:off` comment tag to turn off your IDE code formatter:

[,java]
----
import objectos.code.JavaTemplate;

public class Tutorial extends JavaTemplate {
  @Override
  protected final void definition() {
    // @formatter:off
    _package("com.example");

    _public(); _final(); _class("Tutorial"); _body();
  }
}
----

This tutorial will use the latter from now on.

== Installation

To use Objectos Code in your project add the following to your POM:

[,xml]
----
<dependencies>
    <dependency>
        <groupId>br.com.objectos</groupId>
        <artifactId>objectos-code</artifactId>
    </dependency>
</dependencies>
----

This assumes you are using the ilink:intro/install[Objectos BOM POM].
