= Implementations reject `null` values

All of the the Objectos Util provided `java.util.Collection` implementations reject `null` values.

The rejection occurs in a _fail-fast_ manner;
a `NullPointerException` is thrown as soon as an attempt to add a `null` value occurs.

An an example, consider the following code:

[,java]
----
var list = new GrowableList<String>();

list.add(null);
----

It tries to add a `null` value to a `GrowableList`.
At runtime, this code fails with an uncaught `NullPointerException`:

----
java.lang.NullPointerException: e == null
	at objectos.lang.Check.notNull(Check.java:150)
	at objectos.util.GrowableList.add(GrowableList.java:125)
----

Notice the exception's message: `e == null`.
Depending on your use-case, this message from the `NullPointerException` might be cryptic.

The `GrowableCollection` interface provides methods that allows you to specify a different message to the thrown `NullPointerException`. 

== The `addWithNullMessage` method

You can control the message via the `addWithNullMessage` method.
This method is defined in the `GrowableCollection` interface.

Take the following `OrderBuilder` example:

[,java]
----
import objectos.util.GrowableList;

public class OrderBuilder {
  private final GrowableList<Item> items = new GrowableList<>();

  public final void add(Item item) {
    items.addWithNullMessage(item, "item == null");
  }
  
  ...
}
----

If the `OrderBuilder.add` method is invoked with a `null` item like so:

[,java]
----
var builder = new OrderBuilder();

builder.add(null);
----

It fails with a `NullPointerException` having the `item == null` message:

----
java.lang.NullPointerException: item == null
	at objectos.lang.Check.notNull(Check.java:150)
	at objectos.util.GrowableList.addWithNullMessage(GrowableList.java:249)
----

== The `addWithNullMessage` method variant

The `GrowableCollection` offers a `addWithNullMessage(String, int, String)` variant.
It is meant to be used when adding a sequenced container such as an array, a `List` or an `Iterator`:  

[,java]
----
import objectos.lang.Check;
import objectos.util.GrowableList;

public class OrderBuilder {
  private final GrowableList<Item> items = new GrowableList<>();

  ...

  public final void addAll(Item... items) {
    Check.notNull(items, "items == null");

    for (int i = 0; i < items.length; i++) {
      this.items.addWithNullMessage(items[i], "items[", i, "] == null");
    }
  }
}
----

When the `OrderBuilder.addAll` method is invoked like so:

[,java]
----
var builder = new OrderBuilder();

builder.addAll(
  new Item("A"),
  new Item("B"),
  null,
  new Item("D")
);
----

It fails with a `NullPointerException` having the `items[2] == null` message:

----
java.lang.NullPointerException: items[2] == null
	at objectos.lang.Check.notNull(Check.java:189)
	at objectos.util.GrowableList.addWithNullMessage(GrowableList.java:283)
----

== `GrowableSet` behaves similarly

As a final reminder, know that the `GrowableSet` class has the same behavior regarding `null` values.

In other words, the examples in this section would behave the same way if you were to replace the `GrowableList` with a `GrowableSet`. 