= User guide

Objectos Util provides pairs of growable-unmodifiable implementations meant to be used in tandem.

== Use the `Growable` as a builder of the `Unmodifiable`

The primary use-case is to use a growable implementation as the builder of the unmodifiable one.

Suppose you have the following Java record representing the metadata of a blog post:

[,java]
----
import java.util.Set;

public record Post(String title,
                   Set<String> tags) {}
----

Let's create a builder for it.
One possible solution is:  

[,java]
----
import objectos.lang.Check;
import objectos.util.GrowableSet;

public class PostBuilder {
  private String title = "Untitled";

  private final GrowableSet<String> tags = new GrowableSet<>();

  public final Post build() {
    return new Post(
      title,

      tags.toUnmodifiableSet()
    );
  }

  public final PostBuilder tag(String tag) {
    tags.add(tag);

    return this;
  }

  public final PostBuilder title(String title) {
    this.title = Check.notNull(title, "title == null");

    return this;
  }
}
----

Notice how we have used a `GrowableSet` to provide an `UnmodifiableSet` instance to our `Post` instance.  

== Implementations reject `null` values

One important thing to know about the Objectos Util collections is that they all reject `null` values.

Additionally, all of the `java.util.Map` implementations also reject `null` keys.

=== Using the `addWithNullMessage` method

As 

== All collections implements `objectos.lang.ToStringObject`

== You cant create an UnmodifiableList or UnmodifiableSet directly
