= User guide

Objectos Utils provides implementations that are _special-purpose_.

They are not meant to be a replacement to the ones provided by the JDK.

== Use the `Growable` as a builder of the `Unmodifiable`

Objectos Util provides pairs of growable-unmodifiable implementations meant to be used in tandem.

The primary use-case is to use a growable implementation as the builder of the unmodifiable one.

Suppose you have the following Java record representing the metadata of a blog post:

[,java]
----
import java.util.Set;

public record Post(String title,
                   Set<String> tags) {}
----

Let's create a builder for it.
One possible solution is:  

[,java]
----
import objectos.lang.Check;
import objectos.util.GrowableSet;

public class PostBuilder {
  private String title = "Untitled";

  private final GrowableSet<String> tags = new GrowableSet<>();

  public final Post build() {
    return new Post(
      title,

      tags.toUnmodifiableSet()
    );
  }

  public final PostBuilder tag(String tag) {
    tags.add(tag);

    return this;
  }

  public final PostBuilder title(String title) {
    this.title = Check.notNull(title, "title == null");

    return this;
  }
}
----

Notice how we have used a `GrowableSet` to provide an `UnmodifiableSet` to our `Post` instance.  

== Implementations reject `null` values

One important thing to know about the Objectos Util collections is that they all reject `null` values.

Additionally, all of the `java.util.Map` implementations also reject `null` keys.

=== Using the `add` method

A `GrowableList` or a `GrowableSet` instance will fail with a `NullPointerException` when the `add` method is invoked with a `null` element.

For example, the following code

[,java]
----
var list = new GrowableList<String>();

String nullString = null;

list.add(nullString);
----

Fails with an uncaught `NullPointerException`:

----
java.lang.NullPointerException: e == null
	at objectos.lang.Check.notNull(Check.java:150)
	at objectos.util.GrowableList.add(GrowableList.java:125)
----

With the `e == null` message.

=== Using the `addWithNullMessage` method

Depending on your use-case, the `e == null` message from the `NullPointerException` might be cryptic.

You can control the message via the `addWithNullMessage` method.
This method is defined in the `GrowableCollection` interface.
Both `GrowableList` and `GrowableSet` implements it.

Take the following `OrderBuilder` example:

[,java]
----
import objectos.util.GrowableList;

public class OrderBuilder {
  private final GrowableList<Item> items = new GrowableList<>();

  public final void add(Item item) {
    items.addWithNullMessage(item, "item == null");
  }
  
  ...
}
----

If the `OrderBuilder.add` method is invoked with a `null` item like so:

[,java]
----
var builder = new OrderBuilder();

builder.add(null);
----

It fails with a `NullPointerException` having the `item == null` message:

----
java.lang.NullPointerException: item == null
	at objectos.lang.Check.notNull(Check.java:150)
	at objectos.util.GrowableList.addWithNullMessage(GrowableList.java:249)
----

=== Using the `addWithNullMessage` method variant

The `GrowableCollection` offers a `addWithNullMessage(String, int, String)` variant.
It is meant to be used when adding a sequenced container such as an array, a `List` or an `Iterator`:  

[,java]
----
import objectos.lang.Check;
import objectos.util.GrowableList;

public class OrderBuilder {
  private final GrowableList<Item> items = new GrowableList<>();

  ...

  public final void addAll(Item... items) {
    Check.notNull(items, "items == null");

    for (int i = 0; i < items.length; i++) {
      this.items.addWithNullMessage(items[i], "items[", i, "] == null");
    }
  }
}
----

When the `OrderBuilder.addAll` method is invoked like so:

[,java]
----
var builder = new OrderBuilder();

builder.addAll(
  new Item("A"),
  new Item("B"),
  null,
  new Item("D")
);
----

It fails with a `NullPointerException` having the `items[2] == null` message:

----
java.lang.NullPointerException: items[2] == null
	at objectos.lang.Check.notNull(Check.java:189)
	at objectos.util.GrowableList.addWithNullMessage(GrowableList.java:283)
----

== All collections implements `objectos.lang.ToStringObject`

All of the Objectos Util provided implements the ilink:objectos-lang/ToString[`ToStringObject.Formattable`] interface.

It means they all provide _human-readable_ string representations.
The main use-case is to help during debugging sessions.

=== `Collection` examples

Consider the following Java record:

[,java]
----
public record City(String name) {}
----

The following Java program:

[,java]
----
var cities = new GrowableList<City>();

cities.add(new City("São Paulo"));
cities.add(new City("Piracicaba"));
cities.add(new City("São José dos Campos"));

System.out.println(cities);
----

Generates the output:

----
GrowableList [
  0 = City[name=São Paulo]
  1 = City[name=Piracicaba]
  2 = City[name=São José dos Campos]
]
----

=== `Map` examples

The Objectos Util `java.util.Map` implementations also produce a _human-readable_ `toString` output.

For example, consider the following that maps Brazilian states to a few of their cities: 

[,java]
----
var states = new GrowableMap<State, List<City>>();

var cities = new GrowableList<City>();

cities.add(new City("São Paulo"));
cities.add(new City("Piracicaba"));
cities.add(new City("São José dos Campos"));

states.put(new State("SP"), cities.toUnmodifiableList());

cities.clear();

cities.add(new City("Belém"));
cities.add(new City("Santarém"));
cities.add(new City("Tomé-Açu"));

states.put(new State("PA"), cities.toUnmodifiableList());

System.out.println(states);
----

It produces the following output:

----
GrowableMap [
  State[abbr=SP] = UnmodifiableList [
    0 = City[name=São Paulo]
    1 = City[name=Piracicaba]
    2 = City[name=São José dos Campos]
  ]
  State[abbr=PA] = UnmodifiableList [
    0 = City[name=Belém]
    1 = City[name=Santarém]
    2 = City[name=Tomé-Açu]
  ]
]
----

Note that `State` is a Java record:

[,java]
----
public record State(String abbr) {}
----

== You cant create an UnmodifiableList or UnmodifiableSet directly
