= Array Utilities

Objectos Util provides utilities for working with arrays.

== Singleton zero-length instances

As a convenience Objectos Util provides singleton zero-length array instances.
You can access them via the following methods:

* `ByteArrays::empty`
* `DoubleArrays::empty`
* `IntArrays::empty`
* `ObjectArrays::empty`

== The `growIfNecessary` method

If you need to implement a "growable" array, Objectos Util provides a utility for that.

The following example uses the `IntArrays::growIfNecessary` method to create a bare-bones `IntList`:

[,java]
----
import objectos.util.IntArrays;

public class IntList {
  private int[] data = IntArrays.empty();

  private int cursor = 0;

  public boolean add(int value) {
    data = IntArrays.growIfNecessary(data, cursor);
    data[cursor++] = value;
    return true;
  }

  public int get(int index) {
    return data[index];
  }
}
----

The `growIfNecessary` method accepts two arguments:

- the first one is the array that needs to be grown (if necessary); and
- the second one is the array index where you want to store the element.

If the specified array index is greater than the array length, `growIfNecessary` will:

* create a new empty array.
The new array will be large to hold the element at the specified index; and
* copy the all of the elements from the old array into the new one.

This method is also available for other array types:

* `ByteArrays::growIfNecessary`
* `CharArrays::growIfNecessary`
* `DoubleArrays::growIfNecessary`
* `IntArrays::growIfNecessary`
* `ObjectArrays::growIfNecessary`