= Field name

Use the `name` instruction to define the name of the generated field declaration.

You can specify the name as a string value, like so:

[,java]
----
import objectos.code.JavaTemplate;

public class FieldName01 extends JavaTemplate {
  @Override
  protected final void definition() {
    classDeclaration(
      name("FieldName"),

      field(
        INT, name("myFieldName")
      )
    );
  }
}
----

The code above generates:

[,java]
----
class FieldName {
  int myFieldName;
}
----

== Multiple names

When multiple names are specified, the field declaration is generated with multiple variable declarators.

The following Objectos Code:

[,java]
----
import objectos.code.JavaTemplate;

public class FieldName02 extends JavaTemplate {
  @Override
  protected final void definition() {
    classDeclaration(
      name("MultipleNames"),

      field(
        INT, name("a"), name("b"), name("c")
      ),

      field(
        BOOLEAN, name("d"), name("e"), name("f")
      )
    );
  }
}
----

Generates:

[,java]
----
class MultipleNames {
  int a, b, c;

  boolean d, e, f;
}
----

== Unnamed field

If you don't specify a name for your field declaration it will be generated with the `unnamed` name.

The following Objectos Code:

[,java]
----
import objectos.code.JavaTemplate;

public class FieldName03 extends JavaTemplate {
  @Override
  protected final void definition() {
    classDeclaration(
      name("Unnamed"),

      field(INT),

      field(DOUBLE)
    );
  }
}
----

Generates:

[,java]
----
class Unnamed {
  int unnamed;

  double unnamed;
}
----

== Invalid names

The `name(String)` instruction will reject names that contain invalid characters for a Java identifier.

The following Objectos Code:

[,java]
----
import objectos.code.JavaTemplate;

public class FieldName04 extends JavaTemplate {
  @Override
  protected final void definition() {
    classDeclaration(
      name("InvalidNames"),

      field(INT, name("foo.bar"))
    );
  }
}
----

Fails with the following exception:

----
Exception in thread "main" java.lang.IllegalArgumentException: The string foo.bar is an invalid identifier:

It must not contain a '.' character.

	at objectos.code.internal.JavaModel.checkName(JavaModel.java:187)
	at objectos.code.internal.JavaModel.checkIdentifier(JavaModel.java:27)
	at objectos.code.JavaTemplate.name(JavaTemplate.java:2371)
	at objectos.docs.code.field.FieldName04.definition(FieldName04.java:20)
	(...)
----

== Invalid names: caveat

Please note that the `name(String)` instruction will only check for invalid characters in identifiers.
It does not check if a string containing only valid identifier characters makes up a valid identifier.

In other words, the following Objectos Code executes normally:

[,java]
----
import objectos.code.JavaTemplate;

public class FieldName05 extends JavaTemplate {
  @Override
  protected final void definition() {
    classDeclaration(
      name("Caveat"),

      field(INT, name("break"))
    );
  }
}
----

It generates the following Java code:

[,java]
----
class Caveat {
  int break;
}
----

Note that `break`, even though does not contain invalid characters for an identifier, is not a valid identifier:
`break` is a reserved keyword.