= Using the `NoteSink` interface

After declaring your note instances you can send them by using the `NoteSink` interface.

In this section we will give you instructions on how to use the `NoteSink` interface.

== Obtaining `NoteSink` instances

As seen in the previous section notes are bound to a particular class as, by default,
their source is set to the fully qualified name of the class in which the note was declared.

The first thing to know about `NoteSink` instances is that, unlike notes,
`NoteSink` instances _are not bound_ to a particular class. Typically
`NoteSink` instances *will not be* `static final` fields of a class.

Next we will discuss the recommended strategies for obtaining `NoteSink` instances.

=== Via constructor

This is the recommended way to obtain `NoteSink` instances. In particular for
the long-lived objects of your Java application.

[,java]
----
import objectos.lang.*;

public class Service {
  private final NoteSink sink;

  Service(NoteSink sink) {
    this.sink = sink;
  }
}
----

=== Via method parameter

If you are concerned about object size and garbage creation, storing the `NoteSink`
in an instance field might be problematic. If the class or the method where the
noting takes place is not part of a public API, you can pass the `NoteSink` via a method parameter.

[,java]
----
import objectos.lang.*;

public class ShortLived {
  void internalMethod(NoteSink sink) {
    // use sink here
  }
}
----

=== Via setter method

The previous option might not work for you if the method where the noting takes place
is part of the exported API. In this case you can use a setter method for the `NoteSink` instance.

[,java]
----
import objectos.lang.*;

public class Setter {
  private NoteSink sink = NoOpNoteSink.getInstance();

  void setNoteSink(NoteSink sink) {
    if (sink == null) {
      throw new NullPointerException("sink == null");
    }

    this.sink = sink;
  }
}
----

You must be aware this strategy is error-prone:

* you must null-check before setting the `sink` field value;
* you must set the `sink` to a default value to avoid null-pointer exceptions. Typically this
will be the ilink:v0002/objectos-lang/note-sink-api/the-no-op-note-sink[`NoOpNoteSink`]; and
* depending on your requirements, you might need some sort of synchronization.

=== Via static factory

As a last resort, you can create your own static factory. Since we consider it a last
resort, Objectos Lang does not provide one out-of-the-box. A minimal example is:

[,java]
----
import objectos.lang.*;

public final class StaticNoteSink {
  private static NoteSink SINK = NoOpNoteSink.getInstance();

  private StaticNoteSink() {}

  public static NoteSink get() {
    return SINK;
  }

  public static void set(NoteSink sink) {
    if (sink == null) {
      throw new NullPointerException("sink == null");
    }

    SINK = sink;
  }
}
----

During application initialization, set the static factory with a proper `NoteSink` instance.
Then, in the class where noting is needed, you can obtain the sink from the factory.

[,java]
----
import objectos.lang.*;

public class Service {
  private static final NoteSink SINK = StaticNoteSink.get();
}
----

Consider using this strategy as a last resort as it can make using sinks
for debugging more complicated. Also this strategy is error-prone for the same reasons as
the _setter method_ strategy.

== Sending notes

Now that you have:

* your notes declared; and
* obtained a `NoteSink` instance.

You can send notes.

To send notes you invoke one of the `send` methods from the `NoteSink` interface.
The `NoteSink` interface provides a different `send` method for each `Note` subclass.

=== `Note0`

Notes of the `Note0` are not parameterized:

[,java]
----
static final Note0 NOTE = Note0.info();
----

To send a note you invoke the `send` method passing the note as a parameter:

[,java]
----
sink.send(NOTE);
----

=== `Note1`

Notes of the `Note1` class have a single type argument.
In order to send these notes you must pass an object
of the same type as the type argument of the note.

For example, if the note is parameterized with a hypothetical `Result` type:

[,java]
----
static final Note1<Result> NOTE = Note1.info();
----

You must invoke the `send` method passing, along with the note itself, a `Result` instance:

[,java]
----
Result result = computeResult();
sink.send(NOTE, result);
----

=== `Note2`

In a similar way, invoking the `send` method with `Note2` notes requires you to
pass, along with the note instance itself, two additional objects.
The two objects must have the same types, in order, as those declared as
type arguments of the note.

So, if the note is declared as:

[,java]
----
static final Note2<Data, Result> NOTE = Note2.info();
----

Then the `send` method must be invoked with the arguments in the following order:

* the note itself;
* a `Data` object; and
* a `Result` object.

[,java]
----
Data input = getInput();
Result result = compute(input);
sink.send(NOTE, input, result);
----

If we were to reverse the order of the type arguments in the note declaration:

[,java]
----
static final Note2<Result, Data> NOTE = Note2.info();
----

Then the `send` method invocation needs to be changed to:

[,java]
----
sink.send(NOTE, result, input);
----

=== `Note3`

Logging `Note3` notes work in a similar way as `Note2`. If the note is parameterized,
in order, with the hypothetical types `A`, `B` and `C`:

[,java]
----
static final Note3<A, B, C> NOTE = Note3.info();
----

Then a `send` method invocation would need to be:

[,java]
----
sink.send(NOTE, a, b, c);
----

Where `a`, `b` and `c` are objects of types `A`, `B` and `C` respectively.
