= Assignment Operator

Here is a quick overview of the assignment operator in Objectos Code:

[,java]
----
// Objectos Code
block(
  n("a"), gets(), n("b"), end(),
	
  n("x"), gets(), n("y"), gets(), n("z"), end(),
  
  n("barArray"), dim(i(0)), gets(), _new(t("foo", "Bar")), end(),
	
  invoke("m"), n("foo"), gets(), invoke("n"), end(),

  invoke("foo", n("i"), gets(), n("j"))
);

// Generated code
{
  a = b;
  x = y = z;
  barArray[0] = new foo.Bar();
  m().foo = n();
  foo(i = j);
}
----

Next we will discuss each operator individually.

== Simple assignment operator

In Objectos Code, the `gets()` instruction represents the simple assignment operator `=`.

You use it between the left-hand side (LHS) and the right-hand side (RHS) of the https://docs.oracle.com/javase/specs/jls/se19/html/jls-15.html#jls-15.26.1[expression].

Next we will look at the different examples of both the LHS and RHS.

=== LHS is a expression name

The following example assigns the value of the variable `value` to the variable `x`: 

[,java]
----
n("x"), gets(), n("value")

x = value;
----

If variable `x` is the field of the type of a variable `foo` our LHS becomes:

[,java]
----
n("foo"), n("y"), gets(), n("value")

foo.y = value;
----

To assign the static field of a type you would also use an expression name.
The syntax is different though:

[,java]
----
t("com.example", "MyType"), n("field"), gets(), n("value")

com.example.MyType.field = value;
----

The syntax is different so that Objectos Code can automatically generate an import declaration if requested.
The output would be something along the lines:

[,java]
----
import com.example.MyType;

MyType.field = value;
----

Let's look at field access expressions next.

=== LHS is a field access expression

You might want to assign a value to the field of a reference that is provided by a primary expression.

An useful example is when using the `_this()` instruction, like so:

[,java]
----
_this(), n("x"), gets(), n("x"),
_this(), n("y"), gets(), n("y")

this.x = x;
this.y = y;
----

In the following example the reference is returned by a method invocation:

[,java]
----
invoke("point"), n("x"), gets(), n("valueX"), end(),
invoke("point"), n("y"), gets(), n("valueY"), end()

point().x = valueX;
point().y = valueY;
----

The primary expression can also start with an expression name:

[,java]
----
n("a"), invoke("b"), n("x"), gets(), n("value"), end() 

n.b().x = value;
----

Let's look at array access expressions next.

=== LHS is an array access expression

In Objectos Code, to assign values to the components of an array reference you write the following:

[,java]
----
n("elements"), dim(i(0)), gets(), n("e0"), end(),
n("elements"), dim(i(1)), gets(), n("e1"), end(),
n("elements"), dim(i(2)), gets(), n("e2"), end()

elements[0] = e0;
elements[1] = e1;
elements[2] = e2;
----

It also works with multidimensional arrays:

[,java]
----
n("multi"), dim(n("x")), dim(n("y")), gets(), n("value"), end()

mulit[x][y] = value;
----

The array reference might be given by a method invocation expression:

[,java]
----
invoke("arrayRef"), dim(invoke("index")), gets(), n("value"), end()

arrayRef()[index()] = value;
----

Next, let's look at the right-hand side of the expression.

=== Other RHS examples

An assignment expression can be the RHS of another assignment expression:

[,java]
----
n("a"), gets(), n("b"), gets(), n("c"), end(),
n("name"), gets(), invoke("foo"), n("name"), gets(), n("value"), end()

a = b = c;
name = foo().name = value;
----

More generally, any expression can be at the RHS:

[,java]
----
n("index"), gets(), i(123), end(),
n("name"), gets(), s("Some Name"), end(),
n("foo"), gets(), _new(t("com.example", "Foo")), end()

index = 123;
name = "Some Name";
foo = new com.example.Foo();
----

We will look at the compound assignment operators at the next section.

== Compound assignment operators

The compound assignment operators are not supported at the moment.