= Assignment Operator

Here is a quick overview of the assignment operator in Objectos Code:

[,java]
----
// Objectos Code
block(
  n("a"), gets(), n("b"), end(),
	
  n("x"), gets(), n("y"), gets(), n("z"), end(),
  
  n("barArray"), dim(i(0)), gets(), _new(t("foo", "Bar")), end(),
	
  invoke("m"), n("foo"), gets(), invoke("n"), end(),

  invoke("foo", n("i"), gets(), n("j"))
);

// Generated code
{
  a = b;
  x = y = z;
  barArray[0] = new foo.Bar();
  m().foo = n();
  foo(i = j);
}
----

Next we will discuss each operator individually.

== Simple assignment operator

In Objectos Code, the `gets()` instruction represents the simple assignment operator `=`.
You use it between the left-hand side (LHS) and the right-hand side (RHS) of the https://docs.oracle.com/javase/specs/jls/se19/html/jls-15.html#jls-15.26.1[expression].

The LHS of the expression can be one of the following:

* expression name;
* field access expression; or
* array access expression.

Let's look at them individually.

=== LHS is a expression name

The following example assigns the value of the variable `value` to the variable `x`: 

[,java]
----
n("x"), gets(), n("value")

x = value;
----

If variable `x` is the field of the type of a variable `foo` our LHS becomes:

[,java]
----
n("foo"), n("y"), gets(), n("value")

foo.y = value;
----

To assign the static field of a type you would also use an expression name.
The syntax is different though:

[,java]
----
t("com.example", "MyType"), n("field"), gets(), n("value")

com.example.MyType.field = value;
----

The syntax is different so that Objectos Code can automatically generate an import declaration if requested.
The output would be something along the lines:

[,java]
----
import com.example.MyType;

MyType.field = value;
----

Let's look at field access expressions next.

== Compound assignment operators

The compound assignment operators are not supported at the moment.